name: Export KiCad Images

on:
  push:
    branches: [main]
    paths:
      - 'kicad/**'
  workflow_dispatch:

permissions:
  contents: write

jobs:
  export:
    uses: zeulewan/shared-workflows/.github/workflows/export-kicad-images.yml@main
